import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const source=readFileSync('app.js','utf8');
function setup(hash=''){
 const nodes=new Map(), events=new Map();let points=0;
 const context={fillRect(){},createRadialGradient(){return {addColorStop(){}}},beginPath(){},moveTo(x,y){assert.ok(Number.isFinite(x)&&Number.isFinite(y));points++},lineTo(x,y){assert.ok(Number.isFinite(x)&&Number.isFinite(y));points++},stroke(){},fillText(){}};
 function node(key){if(!nodes.has(key))nodes.set(key,{width:300,height:150,value:'',textContent:'',checked:false,classList:{add(){},remove(){}},setAttribute(){},addEventListener(type,fn){events.set(key+':'+type,fn)},getBoundingClientRect(){return {width:600,height:620}},getContext(){return context},showModal(){},close(){}});return nodes.get(key)}
 let copied='',downloaded='';const realm={document:{querySelector:node,querySelectorAll(){return ['wild','calm','dreamy','electric'].map(m=>{let n=node('mood:'+m);n.value=m;return n})},hidden:false,createElement(type){if(type==='canvas')return {getContext(){return context},toBlob(fn){fn(new Blob(['image']))}};return {click(){downloaded=this.download}}}},window:{addEventListener(){},prompt(){}},navigator:{clipboard:{async writeText(t){copied=t}}},location:{hash,href:'https://habiv.example/'+hash},URL,URLSearchParams,Blob,Math,Uint32Array,crypto:globalThis.crypto,matchMedia(){return {matches:true}},devicePixelRatio:1,ResizeObserver:class{observe(){}},requestAnimationFrame(){return 1},setTimeout(){return 1},clearTimeout(){}};
 vm.createContext(realm);vm.runInContext(source,realm);return {realm,node,events,get points(){return points},get copied(){return copied},get downloaded(){return downloaded},run:s=>vm.runInContext(s,realm)};
}
test('orbit is deterministic, name-sensitive, and every coordinate is finite',()=>{let s=setup();assert.ok(s.points>30000);assert.equal(s.run('geometry({name:"Neeraj",mood:"wild"}).seed'),s.run('geometry({name:" neeraj ",mood:"wild"}).seed'));assert.notEqual(s.run('geometry({name:"Neeraj",mood:"wild"}).seed'),s.run('geometry({name:"Neeraj",mood:"calm"}).seed'));for(const mood of ['wild','calm','dreamy','electric'])s.run(`update({name:"Test",mood:"${mood}"},false)`);});
test('shared inputs restore safely and invalid mood falls back',()=>{let s=setup('#name=%3Cimg%20onerror%3Dx%3E&mood=unknown');assert.equal(s.node('#art-name').textContent,'<img onerror=x>’s orbit.');assert.equal(s.run('current.mood'),'wild');s.run('update({name:"test",mood:"__proto__"},false)');assert.equal(s.run('current.mood'),'wild');s.run('update({name:"a".repeat(100),mood:"calm"},false)');assert.equal(s.run('current.name.length'),32);});
test('form updates displayed art and share URL round-trips chosen state',async()=>{let s=setup();s.node('#name').value='Me & you 🪐';s.node('input[name="mood"]:checked').value='dreamy';s.events.get('#creator:submit')({preventDefault(){}});assert.equal(s.node('#art-name').textContent,'Me & you 🪐’s orbit.');await s.events.get('#share:click')();let restored=setup(new URL(s.copied).hash);assert.equal(restored.node('#art-name').textContent,'Me & you 🪐’s orbit.');assert.equal(restored.run('current.mood'),'dreamy');});
test('save creates PNG download and pause toggles',()=>{let s=setup();s.events.get('#save:click')();assert.equal(s.downloaded,'habiv-orbit.png');assert.equal(s.run('paused'),true);s.events.get('#pause:click')();assert.equal(s.run('paused'),false);});
